export const BankCoopEnum = [
  { key: "BANCO_PICHINCHA", value: "Banco Pichincha" },
  { key: "BANCO_INTERNACIONAL", value: "Banco Internacional" },
  { key: "BANCO_GUAYAQUIL", value: "Banco Guayaquil" },
  { key: "BANCO_PACIFICO", value: "Banco Pacifico" },
  { key: "BANCO_PRODUCCION", value: "Banco Produccion" },
  { key: "BANCO_BOLIVARIANO", value: "Banco Bolivariano" },
  { key: "BANCO_AUSTRO", value: "Banco Austro" },
  { key: "BANCO_DEL_AHORRO", value: "Banco del Ahorro" },
  { key: "BANCO_MACHALA", value: "Banco Machala" },
  { key: "BANCO_SOLIDARIO", value: "Banco Solidario" },
  { key: "BANCO_LOJA", value: "Banco Loja" },
  { key: "BANCO_AMAZONAS", value: "Banco Amazonas" },
  { key: "BANCO_DINERS", value: "Banco Diners" },
  { key: "BANCO_FINCA", value: "Banco Finca" },
  { key: "BANCO_GENERAL_RUMIÑAHUI", value: "Banco General Rumiñahui" },
  { key: "BANCO_COOPNACIONAL", value: "Banco Coopnacional" },
  { key: "COOP_JEP", value: "Cooperativa JEP" },
  {
    key: "COOP_MUSHUC_RUNA",
    value: "Cooperativa de Ahorro y Crédito Mushuc Runa",
  },
  { key: "COOP_CHORDELEG", value: "Cooperativa de Ahorro y Crédito Chordeleg" },
  {
    key: "COOP_JARDIN_AZUAYO",
    value: "Cooperativa de Ahorro y Crédito Jardín Azuayo",
  },
  {
    key: "COOP_POLICIA_NACIONAL",
    value: "Cooperativa de Ahorro y Crédito Policía Nacional",
  },
  {
    key: "COOP_COOPROGRESO",
    value: "Cooperativa de Ahorro y Crédito Cooprogreso",
  },
  {
    key: "COOP_29_OCTUBRE",
    value: "Cooperativa de Ahorro y Crédito 29 de Octubre",
  },
  { key: "COOP_CACPECO", value: "Cooperativa de Ahorro y Crédito Cacpeco" },
  { key: "COOP_RIOBAMBA", value: "Cooperativa de Ahorro y Crédito Riobamba" },
  { key: "COOP_OSCUS", value: "Cooperativa de Ahorro y Crédito Oscus" },
  { key: "COOP_COOPMEGO", value: "Cooperativa de Ahorro y Crédito Coopmego" },
  {
    key: "COOP_ALIANZA_VALLE",
    value: "Cooperativa de Ahorro y Crédito Alianza del Valle",
  },
];
