import "./globals.css";

import { Inter } from "next/font/google";

import Toaster from "./Toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LookPay",
  description: "Generated by create next app",
  icon: "/favicon.ico",
};

export default function RootLayout({
  children,
}: {

  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
